remote_theme: thuhcsi/slate
title: {HILvoice: Human-in-the-Loop Style Selection for Elder-Facing Speech Synthesis}
description: Published on ISCSLP 2022
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
